//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trading.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trading.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Article_Marketing_icon_icons_com_53705 {
            get {
                object obj = ResourceManager.GetObject("Article-Marketing_icon-icons.com_53705", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ethereum
        ///Tether
        ///BNB
        ///USD Coin
        ///XRP
        ///Terra
        ///Solana
        ///Cardano
        ///Avalanche
        ///Polkadot
        ///Binance USD
        ///Dogecoin
        ///TerraUSD
        ///SHIBA INU
        ///Wrapped Bitcoin
        ///Polygon
        ///Cronos
        ///Dai
        ///Cosmos
        ///Litecoin
        ///NEAR Protocol
        ///Chainlink
        ///Uniswap
        ///TRON
        ///FTX Token
        ///UNUS SED LEO
        ///Bitcoin Cash
        ///Algorand
        ///Stellar
        ///Decentraland
        ///Bitcoin BEP2
        ///Hedera
        ///The Sandbox
        ///Ethereum clásico
        ///Internet Computer
        ///Elrond
        ///Monero
        ///Fantom
        ///Filecoin
        ///VeChain
        ///Klaytn
        ///Axie Infinity
        ///Waves
        ///Theta Network
        ///THORChain
        ///Tezos
        ///Helium
        ///Zcash
        ///EOS
        ///IOTA
        ///Flow
        ///The G [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string crypto {
            get {
                return ResourceManager.GetString("crypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exchange_dollar_icon_icons_com_53141__3_ {
            get {
                object obj = ResourceManager.GetObject("exchange-dollar_icon-icons.com_53141 (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
